"""initial schema

Revision ID: 02502d6a9728
Revises: 
Create Date: 2026-10-04 13:41:15.676992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02502d6a9728'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_backup_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('entity_type', sa.Enum('property', 'booking', 'expense', 'works', 'furniture', 'coownership_year', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_entity_id'), 'attachment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachment_entity_type'), 'attachment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachment_sha256_hash'), 'attachment', ['sha256_hash'], unique=False)
    op.create_table('coownership_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_part_pct', sa.Float(), nullable=False),
    sa.Column('revenus_bruts', sa.Float(), nullable=False),
    sa.Column('charges', sa.Float(), nullable=False),
    sa.Column('montants_proratises', sa.Boolean(), nullable=False),
    sa.Column('regime_declare', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('montants_a_reporter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surface', sa.Float(), nullable=False),
    sa.Column('date_acquisition', sa.Date(), nullable=False),
    sa.Column('prix_acquisition', sa.Float(), nullable=False),
    sa.Column('frais_notaire', sa.Float(), nullable=False),
    sa.Column('part_terrain_pct', sa.Float(), nullable=False),
    sa.Column('statut_classement', sa.Enum('non_classe', 'classe', name='statutclassement'), nullable=False),
    sa.Column('nb_etoiles', sa.Integer(), nullable=True),
    sa.Column('date_classement', sa.Date(), nullable=True),
    sa.Column('numero_declaration_mairie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_premiere_mise_en_location', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('plateforme', sa.Enum('airbnb', 'booking', 'direct', 'autre', name='plateforme'), nullable=False),
    sa.Column('montant_brut', sa.Float(), nullable=False),
    sa.Column('commission_plateforme', sa.Float(), nullable=False),
    sa.Column('taxe_sejour_collectee', sa.Float(), nullable=False),
    sa.Column('taxe_sejour_reversee_par', sa.Enum('agence_plateforme', 'utilisateur', name='reversementtaxesejour'), nullable=True),
    sa.Column('frais_menage_factures', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('confirmee', 'annulee', name='statutbooking'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('nature', sa.Enum('gros_oeuvre', 'facade_etancheite', 'installations_techniques', 'agencements', name='naturecomposant'), nullable=False),
    sa.Column('part_du_prix_pct', sa.Float(), nullable=False),
    sa.Column('duree_amortissement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant_ttc', sa.Float(), nullable=False),
    sa.Column('fournisseur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categorie', sa.Enum('copropriete', 'assurance', 'taxe_fonciere', 'energie', 'eau', 'internet', 'menage', 'linge', 'entretien', 'frais_plateforme_autres', 'comptabilite', 'interets_emprunt', 'autre', name='categoriecharge'), nullable=False),
    sa.Column('recurrence', sa.Enum('aucune', 'mensuelle', 'trimestrielle', 'annuelle', name='recurrence'), nullable=False),
    sa.Column('recurrence_fin', sa.Date(), nullable=True),
    sa.Column('parent_expense_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_year_carryforward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('annee_origine', sa.Integer(), nullable=False),
    sa.Column('deficit_initial', sa.Float(), nullable=False),
    sa.Column('deficit_restant', sa.Float(), nullable=False),
    sa.Column('amortissements_non_deduits', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furniture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('montant_ttc', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duree_amortissement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant_ttc', sa.Float(), nullable=False),
    sa.Column('fournisseur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nature', sa.Enum('entretien_reparation', 'amelioration', 'construction_agrandissement', name='natureworks'), nullable=False),
    sa.Column('duree_amortissement', sa.Integer(), nullable=True),
    sa.Column('avant_premiere_mise_en_location', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('furniture')
    op.drop_table('fiscal_year_carryforward')
    op.drop_table('expense')
    op.drop_table('building_component')
    op.drop_table('booking')
    op.drop_table('property')
    op.drop_table('coownership_year')
    op.drop_index(op.f('ix_attachment_sha256_hash'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entity_type'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entity_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
