"""ajoute external_id sur investment_transaction pour dedup import IBKR

Revision ID: 09656c8bac99
Revises: 16da40826165
Create Date: 2026-10-04 22:18:23.051486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09656c8bac99'
down_revision: Union[str, None] = '16da40826165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_investment_transaction_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_transaction_external_id'))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
