"""module investissements D1: comptes, titres, transactions

Revision ID: 16da40826165
Revises: b62511f31031
Create Date: 2026-10-04 20:25:49.255932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16da40826165'
down_revision: Union[str, None] = 'b62511f31031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('pea', 'cto', 'autre', name='envelopetype'), nullable=False),
    sa.Column('courtier', sa.Enum('trade_republic', 'ibkr', 'autre', name='courtier'), nullable=False),
    sa.Column('devise_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_ouverture', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticker_yahoo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categorie_allocation', sa.Enum('world', 'europe', 'autre', name='allocationcategorie'), nullable=True),
    sa.Column('dernier_cours', sa.Float(), nullable=True),
    sa.Column('dernier_cours_devise', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dernier_cours_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_isin'), ['isin'], unique=True)

    op.create_table('investment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('achat', 'vente', 'dividende', 'depot', 'retrait', 'frais', 'change', name='typetransaction'), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frais', sa.Float(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['investment_account.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_transaction')
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_isin'))

    op.drop_table('security')
    op.drop_table('investment_account')
    # ### end Alembic commands ###
