"""ajoute taux, duree et date de fin pour les comptes a terme (cash_holding)

Revision ID: 31055affcd98
Revises: daf0583e240a
Create Date: 2026-10-06 15:59:23.521240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31055affcd98'
down_revision: Union[str, None] = 'daf0583e240a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_holding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taux_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duree_mois', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_fin', sa.Date(), nullable=True))

    with op.batch_alter_table('investment_transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('achat', 'vente', 'dividende', 'depot', 'retrait', 'frais', 'change', 'interet', 'retenue_source', name='typetransaction'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('achat', 'vente', 'dividende', 'depot', 'retrait', 'frais', 'change', 'interet', 'retenue_source', name='typetransaction'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('cash_holding', schema=None) as batch_op:
        batch_op.drop_column('date_fin')
        batch_op.drop_column('duree_mois')
        batch_op.drop_column('taux_pct')

    # ### end Alembic commands ###
