"""phase 5: cash holdings, snapshot patrimoine, valorisation bien, categories allocation

Revision ID: 8532ccbabf56
Revises: 16da40826165
Create Date: 2026-10-04 22:36:38.248183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8532ccbabf56'
down_revision: Union[str, None] = '16da40826165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solde', sa.Float(), nullable=False),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_maj', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrimoine_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_snapshot', sa.Date(), nullable=False),
    sa.Column('valeur_actions', sa.Float(), nullable=False),
    sa.Column('valeur_cash', sa.Float(), nullable=False),
    sa.Column('valeur_immobilier', sa.Float(), nullable=False),
    sa.Column('valeur_or', sa.Float(), nullable=False),
    sa.Column('valeur_totale', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patrimoine_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patrimoine_snapshot_date_snapshot'), ['date_snapshot'], unique=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valeur_estimee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valeur_estimee_date', sa.Date(), nullable=True))

    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.alter_column('categorie_allocation',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('world', 'europe', 'emergents', 'or_metal', 'autre', name='allocationcategorie'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.alter_column('categorie_allocation',
               existing_type=sa.Enum('world', 'europe', 'emergents', 'or_metal', 'autre', name='allocationcategorie'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('valeur_estimee_date')
        batch_op.drop_column('valeur_estimee')

    with op.batch_alter_table('patrimoine_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patrimoine_snapshot_date_snapshot'))

    op.drop_table('patrimoine_snapshot')
    op.drop_table('cash_holding')
    # ### end Alembic commands ###
