"""add agency and booking payment date

Revision ID: 857f79d3487d
Revises: 02502d6a9728
Create Date: 2026-10-04 15:15:24.448424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '857f79d3487d'
down_revision: Union[str, None] = '02502d6a9728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commission_pct_defaut', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_paiement', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_booking_agency_id_agency', 'agency', ['agency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_agency_id_agency', type_='foreignkey')
        batch_op.drop_column('date_paiement')
        batch_op.drop_column('agency_id')

    op.drop_table('agency')
    # ### end Alembic commands ###
